export const ACTIVE_PLAYER_HIGHLIGHT_CLASS = "cricket-active-player-pulse";

/** @deprecated Use ACTIVE_PLAYER_HIGHLIGHT_CLASS */
export const ACTIVE_PLAYER_PANEL_CLASS = ACTIVE_PLAYER_HIGHLIGHT_CLASS;

/** @deprecated Use ACTIVE_PLAYER_HIGHLIGHT_CLASS */
export const ACTIVE_PLAYER_SCOREBOARD_CLASS = ACTIVE_PLAYER_HIGHLIGHT_CLASS;
